LibManagement/urls.py
from django.contrib import admin
from django.urls import path, include
from views import Home


urlpatterns = [
    path("admin/", admin.site.urls),  # loads the admin window
    # redirecting user to user home after successfull login
    path("accounts/google/login/callback/libmansys/home",
         include("libmansys.urls")),
    path("accounts/", include("allauth.urls")),
    path("", Home.as_view(), name="home"),  # Website's home page
    path("lib/", include("libmansys.urls")),  # libmansys's home page
]

libmansys/urls.py
from django.urls import path
from . import views
from .views import (
    BookListView,
    BookRequestView,
)

app_name = "libmansys"
urlpatterns = [
    # redirect the user to user home page
    path("", views.user_home, name="user_home"),
    # give details for a book with given ISBN
    path("<int:ISBN>/", views.detail, name="detail"),
    # give details of all books registered in the library system
    path("all/", BookListView.as_view(), name="booklist"),
    # request a new book
    path("request/", BookRequestView.as_view(), name="request"),
    # for changing user profile
    path("profile/", views.edit_profile, name="profile"),
    # give details of pending requests by the user
    path("requests/pending", views.pending_requests, name="pending_requests"),
    # give details of books issued to the user
    path("requests/issued", views.issued_books, name="issued_books"),
]

libmansys/models.py
from pydoc import visiblename
from django.db import models
from django.urls import reverse
from django.core.validators import MaxValueValidator, MinValueValidator


class Book(models.Model):
    name = models.CharField(max_length=50)
    author = models.CharField(max_length=200)
    publisher = models.CharField(max_length=200, default="Not Available")
    isbn = models.PositiveIntegerField()
    genre = models.CharField(max_length=50, default="Not Available")
    summary = models.CharField(max_length=200, default="Not Available")
    location = models.CharField(max_length=200, default="Not Available")
    availability = models.IntegerField(default=0)

    def __str__(self):
        return str(self.name) + " [" + str(self.isbn) + "]"


HOSTEL_CHOICES = (
    ("Rana Pratap Bhawan", "Rana Pratap Bhawan"),
    ("Ashok Bhawan", "Ashok Bhawan"),
    ("Bhagirath Bhawan", "Bhagirath Bhawan"),
    ("Vishwakarma Bhawan", "Vishwakarma Bhawan"),
    ("Krishna Bhawan", "Krishna Bhawan"),
    ("Gandhi Bhawan", "Gandhi Bhawan"),
    ("Shankar Bhawan", "Shankar Bhawan"),
    ("Vyas Bhawan", "Vyas Bhawan"),
    ("Ram Bhawan", "Ram Bhawan"),
    ("Budh Bhawan", "Budh Bhawan"),
    ("Meera Bhawan", "Meera Bhawan"),
    ("NOT YET ALLOTED", "NOT YET ALLOTED"),
)


class Student(models.Model):
    bits_id = models.CharField(max_length=13, default="NOT YET UPDATED")
    # A unique no. generated for every user
    user_ID = models.IntegerField(default=-1)
    mobile_number = models.IntegerField(default=-1,
                                        validators=[
                                            MaxValueValidator(9999999999),
                                            MinValueValidator(1000000000),
                                        ])
    room_no = models.IntegerField(default=-1)
    hostel = models.CharField(
        max_length=50, choices=HOSTEL_CHOICES, default="NOT YET ALLOTED"
    )

    def __str__(self):
        return f"[{self.bits_id}]"


class RequestedBook(models.Model):
    book = models.ForeignKey(
        Book,
        on_delete=models.CASCADE,
    )
    student = models.ForeignKey(
        Student,
        on_delete=models.CASCADE,
    )
    issue = models.BooleanField(
        default=0
    )
    reason = models.CharField(
        max_length=50, default="Provide a reason for rejection"
    )

    def get_absolute_url(self):
        return reverse("libmansys:user_home")

    def __str__(self):
        return str(self.book) + " " + str(self.student) + ""

libmansys/forms.py
from dataclasses import fields
from django.forms import ModelForm
from .models import Student


class NewStudentForm(ModelForm):
    class Meta:
        model = Student
        fields = ["bits_id", "mobile_number", "room_no", "hostel"]

libmansys/views.py
from django.shortcuts import render
from django.template import context
from .models import *
from .functions import is_new_user
from .forms import NewStudentForm
from django.views.generic import ListView, CreateView


def user_home(request):
    """Home page for a logged in user"""
    book_list = Book.objects.all()[:5]
    is_new_user(
        request)  # add a new user to the Student model,do nothing for an existing student
    student = Student.objects.get(user_ID=request.user.id)
    context = {"student": student, "book_list": book_list}
    return render(request, "libmansys/user_home.html", context)


def detail(request, ISBN):
    """Displays the detail of a given book"""
    book = Book.objects.filter(isbn=ISBN)[
        0
    ]  # Stores the book for which details are required

    context = {"book": book}
    return render(request, "libmansys/book_detail.html", context)


class BookListView(ListView):
    """Displays all books available at the library"""

    model = Book
    template_name = "libmansys/book_list.html"
    context_object_name = "book_list"
    ordering = ["name"]


class BookRequestView(CreateView):
    """To request a new book"""

    model = RequestedBook
    fields = ["book"]

    def form_valid(self, form):
        form.instance.student = Student.objects.get(
            user_ID=self.request.user.id)
        return super().form_valid(form)


def edit_profile(request):
    """To edit user profile"""
    student = Student.objects.get(
        user_ID=request.user.id
    )  # store's the current student

    if request.method == "POST":  # runs after the form is submitted
        s_form = NewStudentForm(request.POST, instance=student)
        if s_form.is_valid:
            s_form.save()
        # redirect user to home page
        return render(request, "libmansys/user_home.html")

    else:  # runs when the user wants to change its account details
        s_form = NewStudentForm(instance=student)
        context = {"s_form": s_form}
        return render(request, "libmansys/update_user_profile.html", context)


def pending_requests(request):
    """Displays all books requested by the student"""
    s = Student.objects.get(
        user_ID=request.user.id)  # getting the current user
    book_list = [request.book for request in RequestedBook.objects.filter(
        student=s, issue=False, reason="Provide a reason for rejection")]
    context = {"book_list": book_list}
    return render(request, "libmansys/pending_requests.html", context)


def issued_books(request):
    """Displays all books requested by the student"""
    s = Student.objects.get(
        user_ID=request.user.id)  # getting the current user
    book_list = [request.book for request in RequestedBook.objects.filter(
        student=s, issue=1)]
    context = {"book_list": book_list}
    return render(request, "libmansys/issued_books.html", context)

views.py
from django.views.generic import TemplateView


class Home(TemplateView):
    template_name = "home.html"

libmansys/templates/libmansys/base.html
{%load static%}
<!DOCTYPE html>
<html>

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{%static 'libmansys/main.css'%}">
  <title>Library Management System</title>
</head>


<body>
  <header class="site-header">


    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
      <div class="container">
        <a class="navbar-brand mr-4" href="/">Library Management Portal</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
          aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link" href="{%url 'libmansys:booklist'%}">All Books</a>
            <a class="nav-item nav-link" href="{%url 'libmansys:user_home'%}">Home</a>
          </div>
          <!-- Navbar Right Side -->
          <div class="navbar-nav">
            <a class="nav-item nav-link" href="{%url 'libmansys:request'%}">Request Book</a>
            <a class="nav-item nav-link" href="{%url 'libmansys:profile'%}">View/Change Profile</a>
          </div>
        </div>
      </div>
    </nav>


  </header>


  <main role="main" class="container">
    <div class="row">
      <div class="col-md-8">
        {% block content %}{% endblock %}
      </div>
      <div class="col-md-4">
        <div class="content-section">
          <h3>Our Sidebar</h3>
          <p class='text-muted'>You can put any information here you'd like.
            <ul class="list-group">
              <a class="list-item list-link" href="{%url 'libmansys:pending_requests'%}">Pending Requests</a></ul>
              <a class="list-item list-link" href="{%url 'libmansys:issued_books'%}">Issued Books</a></ul>
          </p>
        </div>
      </div>
    </div>
  </main>


  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
  </script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
  </script>
</body>

</html>

libmansys/templates/libmansys/book_detail.html
{%extends "libmansys/base.html"%}
{%block content%}
<h3>{{book.name}}</h3>
<a>
    <b>Author:</b> {{book.author}}<br>
    <b>Publisher:</b> {{book.publisher}}<br>
    <b>ISBN-10:</b> {{book.isbn}}<br>
    <b>Genre:</b> {{book.genre}}<br>
    <b>Summary:</b> {{book.summary}}<br>
    <b>Location:</b> {{book.location}}<br>
    <b>Availability:</b> {{book.availability}}<br>
</a>
{%endblock content%}

libmansys/templates/libmansys/book_list.html
{%extends "libmansys/base.html"%}
{%block content%}
{% if book_list %}
<ul>
  {%for book in book_list%}
  <article class="media content-section">
    <div class="media-body">
      <div class="book-metadata">
        <a class="mr-2" href="#">{{ book.author }}</a>
        <small class="text-muted">{{ book.isbn }}</small>
      </div>
      <li><a href="{% url 'libmansys:detail' book.isbn %}">
          <h3>{{book.name}}</h3>
        </a></li>
      <p class="book-summary">{{ book.summary }}</p>
    </div>
  </article>
  {%endfor%}
</ul>
{%else%}
<p>No books are available.</p>
{% endif%}

{%endblock content%}

libmansys/templates/libmansys/home.html
{%load socialaccount%}
<h1>Hello {{user.username}}</h1>

libmansys/templates/libmansys/issued_books.html
{%extends "libmansys/base.html"%}
{%block content%}
{% if book_list %}
<ul>
  {%for book in book_list%}
  <article class="media content-section">
    <div class="media-body">
      <div class="book-metadata">
        <a class="mr-2" href="#">{{ book.author }}</a>
        <small class="text-muted">{{ book.isbn }}</small>
      </div>
      <li><a href="{% url 'libmansys:detail' book.isbn %}">
          <h3>{{book.name}}</h3>
        </a></li>
      <p class="book-summary">{{ book.summary }}</p>
    </div>
  </article>
  {%endfor%}
</ul>
{%else%}
<p>No books are available.</p>
{% endif%}

{%endblock content%}

libmansys/templates/libmansys/pending_requests.html
{%extends "libmansys/base.html"%}
{%block content%}
{% if book_list %}
<ul>
  {%for book in book_list%}
  <article class="media content-section">
    <div class="media-body">
      <div class="book-metadata">
        <a class="mr-2" href="#">{{ book.author }}</a>
        <small class="text-muted">{{ book.isbn }}</small>
      </div>
      <li><a href="{% url 'libmansys:detail' book.isbn %}">
          <h3>{{book.name}}</h3>
        </a></li>
      <p class="book-summary">{{ book.summary }}</p>
    </div>
  </article>
  {%endfor%}
</ul>
{%else%}
<p>No books are available.</p>
{% endif%}

{%endblock content%}

libmansys/templates/libmansys/requested_book_form.html
{% extends "libmansys/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Request a Book</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Request</button>
            </div>
        </form> 
    </div>
{% endblock content %}

libmansys/templates/libmansys/update_user_profile.html
{%extends "libmansys/base.html"%}
{%block content%}
<img src="{{ user.socialaccount_set.all.0.get_avatar_url }}" />
<form method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
        <h3>{{user.get_full_name}}</h3>
        </legend>
        <table>
            {{s_form.as_table}}
        </table>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Update and Proceed</button>
        </div>
</form>
{%endblock content%}

libmansys/templates/libmansys/user_home.html
{%extends "libmansys/base.html"%}
{%block content%}
{%load socialaccount%}
<img src="{{ user.socialaccount_set.all.0.get_avatar_url }}" />
<h2>Hello {{user.get_full_name}}</h2>
<a>
    <b>BITS ID:</b> {{student.bits_id}}<br>
    <b>Mobile No. :</b> {{student.mobile_number}}<br>
    <b>Hostel:</b> {{student.hostel}}<br>
    <b>Room No. :</b> {{student.room_no}}<br>
</a>
<br>
<h2>New Arrivals</h2>
<br>
<ul>
    {%for book in book_list%}
    <article class="media content-section">
      <div class="media-body">
        <div class="book-metadata">
          <a class="mr-2" href="#">{{ book.author }}</a>
          <small class="text-muted">{{ book.isbn }}</small>
        </div>
        <li><a href="{% url 'libmansys:detail' book.isbn %}">
            <h3>{{book.name}}</h3>
          </a></li>
        <p class="book-summary">{{ book.summary }}</p>
      </div>
    </article>
    {%endfor%}
  </ul>
{%endblock content%}

templates/home.html
<!-- templates/home.html -->
{% load socialaccount %}

<h1>Library Management System</h1>

<a href="{% provider_login_url 'google' %}">Connect with Google</a>